---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: media-automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: media-automation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - "tailscale-state-sonarr"
      - "tailscale-state-radarr"
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: media-automation
subjects:
  - kind: ServiceAccount
    name: tailscale
    namespace: media-automation
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
